// <auto-generated />
namespace FlightReservationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BackEnd1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BackEnd1));
        
        string IMigrationMetadata.Id
        {
            get { return "201901170019220_BackEnd1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
